# Generated by Django 2.2.24 on 2022-01-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
