# Generated by Django 2.2.24 on 2022-01-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_auto_20220122_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
